### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by Saloed** [alinaib12345/Minesweeper#1]
1. В `pom.xml` не хватает зависимостей `JavaFx`. Из-за этого очень сложно собрать и запустить ваш проект. Что и куда добавлять можно посомтреть [вот здесь](https://openjfx.io/openjfx-docs/#maven). 
2. В `pom.xml` поправьте имя `mainClass` и поскольку у вас диреткория с тестами отличается от лиректории по умолчанию, нужно ещё добавть `testSourceDirectory`.
2. Постарайтесь сделать [это поле](https://github.com/alinaib12345/Minesweeper/blob/a473abe242cbd4f0b48d703f3142980994aefd04/src/main/java/view/Minesweeper.java#L12) не `static`.
3. Местами тут что-то странно работает ![image](https://user-images.githubusercontent.com/8640896/118306526-3ccbb300-b4f2-11eb-85db-b5490f4fe390.png)
4. А почему 30 и 22? Кажется, можно и больше. И хотелось бы в интерфейсе подсказку какую-то. [link](https://github.com/alinaib12345/Minesweeper/blob/a473abe242cbd4f0b48d703f3142980994aefd04/src/main/java/controller/Controller.java#L42)
5. Возможно пересоздавать много элементов интерфейса каждый раз это не очень хорошо. Было бы хорошо как-то понимать, что и у каких элементов поменялось и просто менять у них эти свойства. Без пересоздания. [link](https://github.com/alinaib12345/Minesweeper/blob/a473abe242cbd4f0b48d703f3142980994aefd04/src/main/java/view/View.java#L138)
5. Ещё хотелось бы видеть тесты на интерфейс. Например, что по нажатию кнопки там что-то происходит. Для этого вам может быть удобно использовать библиотеку [`TestFx`](https://github.com/TestFX/TestFX)

**Comment by ghhbdtn** [comment]
> 1. В `pom.xml` не хватает зависимостей `JavaFx`. Из-за этого очень сложно собрать и запустить ваш проект. Что и куда добавлять можно посомтреть [вот здесь](https://openjfx.io/openjfx-docs/#maven).
> 2. В `pom.xml` поправьте имя `mainClass` и поскольку у вас диреткория с тестами отличается от лиректории по умолчанию, нужно ещё добавть `testSourceDirectory`.
> 3. Постарайтесь сделать [это поле](https://github.com/alinaib12345/Minesweeper/blob/a473abe242cbd4f0b48d703f3142980994aefd04/src/main/java/view/Minesweeper.java#L12) не `static`.
> 4. Местами тут что-то странно работает ![image](https://user-images.githubusercontent.com/8640896/118306526-3ccbb300-b4f2-11eb-85db-b5490f4fe390.png)
> 5. А почему 30 и 22? Кажется, можно и больше. И хотелось бы в интерфейсе подсказку какую-то. [link](https://github.com/alinaib12345/Minesweeper/blob/a473abe242cbd4f0b48d703f3142980994aefd04/src/main/java/controller/Controller.java#L42)
> 6. Возможно пересоздавать много элементов интерфейса каждый раз это не очень хорошо. Было бы хорошо как-то понимать, что и у каких элементов поменялось и просто менять у них эти свойства. Без пересоздания. [link](https://github.com/alinaib12345/Minesweeper/blob/a473abe242cbd4f0b48d703f3142980994aefd04/src/main/java/view/View.java#L138)
> 7. Ещё хотелось бы видеть тесты на интерфейс. Например, что по нажатию кнопки там что-то происходит. Для этого вам может быть удобно использовать библиотеку [`TestFx`](https://github.com/TestFX/TestFX)

По 1 пункту: я на java8 делаю, а на сколько я понимаю зависимости с 11+ прописываются для javaFX.
По 3: не могу придумать, как сделать без статической переменной, чтобы у меня не создавались каждый раз новые окна и все изменения происходили в одном окне.
По 7: с тестами для интерфейса пытаюсь разобраться.

**Comment by Saloed** [comment]
1. Кажется, это выржаение никогда не бывает `true` [link](https://github.com/alinaib12345/Minesweeper/blob/391f80849a89ef2826d05a03cb62dba632f25699/src/main/java/view/View.java#L141)
2. Подобный кусок кода встречается в нескольких местах. Хорошо бы убрать дублирование. [link](https://github.com/alinaib12345/Minesweeper/blob/391f80849a89ef2826d05a03cb62dba632f25699/src/main/java/view/View.java#L214-L219)
3. Вот эти числа, 40 и 25, хорошо бы куда-то вынести как именованные константы. [link](https://github.com/alinaib12345/Minesweeper/blob/391f80849a89ef2826d05a03cb62dba632f25699/src/main/java/controller/Controller.java#L46)
4. Кажется, если передать `stage` в `Controller` или `View` при создании, то статическая переменная будет не нужна
